language: scala

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.ivy2/cache/
    - $HOME/.sbt/boot/
    - $HOME/.coursier

sudo: false

matrix:
  include:
  - env: PROJECT=checkstyle
    jdk: oraclejdk8
    script:
    - ./sbt jcheckStyle
  - env: PROJECT=java8
    jdk: oraclejdk8
    script:
    - ./sbt test
    - ./sbt test -J-Dmsgpack.universal-buffer=true
  - env: PROJECT=java11
    jdk: oraclejdk11
    script:
    - ./sbt test
    - ./sbt test -J-Dmsgpack.universal-buffer=true
