language: scala

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.ivy2/cache/
    - $HOME/.sbt/boot/

sudo: false

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

branches:
  only:
    - develop

script:
  - ./sbt jcheckStyle
  - ./sbt test
  - ./sbt test -J-Dmsgpack.universal-buffer=true

matrix:
  include:
  - dist: trusty
    group: edge
    sudo: required
    jdk: oraclejdk9
    scala: 2.12.4
    script:
    - echo "sbt.version=1.0.2" > project/build.properties
    - rm sbt
    - sbt "++ ${TRAVIS_SCALA_VERSION}!" test
    - sbt -Dmsgpack.universal-buffer=true "++ ${TRAVIS_SCALA_VERSION}!" test
